name: Autodocs

on:
  schedule:
  - cron: "30 12 * * *"
    
jobs:
  autodoc:
    name: Generate Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Install Dependencies
      run: |
        tools/travis/install_spaceman_dmm.sh dmdoc
    
    - name: Generate
      run: |
        ~/dmdoc
        touch dmdoc/.nojekyll
      
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2
      with:
        keep_history: true
        build_dir: dmdoc
        jekyll: false
        fqdn: codedocs.yogstation.net
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
